Generating and using key pairs for Owner Attestation
open-horizon/SDO-support pull request #45
Opened 2020-08-27 18:32 UTC by lorenzoking

- Added a function to `run-sdo-owner-services.sh` to allow the use of a local Dockerfile for testing purposes
- Modified `simulate-mfg.sh` to save the original path for public key
- Modified Dockerfile in order to grant correct permissions for key mounting

2020-08-28 18:00 UTC, bmpotter commented on keys/generate-key-pair.sh
> +        privateKey=""${TYPE}"private-key.pem"
Variables in functions should be defined with the `local` keyword, because by default all variables have global scope, which you should avoid.

2020-08-28 18:24 UTC, lorenzoking commented on keys/generate-key-pair.sh
> +    touch Owner-Private-Keystore.p12 Owner-Public-Key.pub && chown user:user Owner-Private-Keystore.p12 Owner-Public-Key.pub
> Why are you touching the files, don't they already exist?

I previously thought you had to touch a file in order to change permissions. :sweat_smile:

2020-08-31 16:58 UTC, lorenzoking commented on keys/generate-key-pair.sh
> +        #printf "%s\n""$q1""%s\n""$q2""%s\n""$q3""%s\n""$q4""%s\n""$q5""%s\n""$q6""%s\n""$q7" | openssl req -x509 -key "$privateKey" -days 365 -out "$CERT"
It was an alternate command that worked doing the same thing. I just left it as a comment in case that option was more appropriate

2020-09-04 16:11 UTC, bmpotter requested changes

2020-09-04 16:11 UTC, bmpotter commented on keys/generate-key-pair.sh
> +    while [[ ${#SDO_KEY_PWD} -lt 6 ]];
You no longer need this `while` loop any more

2020-09-04 16:11 UTC, bmpotter commented on keys/generate-key-pair.sh
> +  else
This `else` isn't needed

2020-09-09 17:00 UTC, bmpotter approved these changes

2020-09-14 13:24 UTC, merged